documentation/working-with-testcafe-studio/README.md

topics links added to Working with TestCafe Studio

---

website/nav/nav-menu.yml

//cc @helen-dikareva @VasilyStrelyaev

adds topics to nav menu

---

website/css/docs.scss

Fix the width of short docs

---

website/css/docs.scss

Make the footer truly sticky.
\cc @MargaritaLoseva

Fix footer stickyness

---

documentation/working-with-testcafe-studio/debugging-tests.md
documentation/working-with-testcafe-studio/organizing-tests.md
documentation/working-with-testcafe-studio/recording-tests.md
documentation/working-with-testcafe-studio/reports.md
documentation/working-with-testcafe-studio/running-tests.md
documentation/working-with-testcafe-studio/writing-test-code.md

Fix pages' permalink

---

website/_sass/_layout.scss
website/css/docs.scss

Fixed menu according to @kirovboris 's remarks
http://strelyaev-w8:8080/
http://strelyaev-w8:8080/documentation/getting-started/

Fix top menu

---

website/css/landing-page.scss

Fix DX logo

---

website/_includes/cookie-notice.html
website/_includes/head.html
website/_layouts/landing.html
website/_sass/_layout.scss
website/scripts/cookie-notice.js

Moved the code to the Studio repository

Add a cookie notice

---

documentation/video-tutorials/README.md
website/_data/videos.json
website/_includes/head.html
website/_includes/video-playlist.html
website/_layouts/post.html
website/css/docs.scss
website/nav/nav-menu.yml
website/scripts/video-playlist.js

\cc @DevExpress/testcafe-docs 
http://strelyaev-w8:8080/documentation/video-tutorials/

Add video playlist to docs

---

website/_includes/head.html
website/css/landing-page.scss
website/index.html
website/scripts/landing-page.js

\cc @MargaritaLoseva @kirovboris

Update Get CTP block

---

website/_data/videos.json
website/_includes/youtube-video-init.html
website/index.html
website/nav/top-menu-items.yml
website/tweets/tweets.json

1) Removed price from the landing page
2) Links to support center filter tickets by product (not category)
3) One tweet changed

Address Natalie's remarks

---

website/_includes/download-page-script.html
website/_layouts/article.html
website/css/article.scss
website/thanks-for-downloading-ctp/index.html

\cc @DevExpress/testcafe-docs 
http://strelyaev-w8:8080/thanks-for-downloading-ctp/

Add a thank you page

---

website/_includes/head.html
website/_includes/header.html
website/_includes/youtube-video-init.html
website/nav/top-menu-items.yml
website/scripts/header.js
website/scripts/landing-page.js
website/scripts/thank-you-page.js
website/thanks-for-downloading-ctp/index.html

Configure analytics

---

website/css/survey.scss
website/scripts/survey.js
website/survey/index.html
website/thanks-for-downloading-ctp/index.html

\cc @kirovboris @churkin @helen-dikareva 
http://strelyaev-w8:8080/survey/

Add a survey

---

website/_includes/download-page-script.html
website/_layouts/article.html
website/scripts/landing-page.js

\cc @DevExpress/testcafe-docs 
Try to click download - does it start?
http://strelyaev-w8:8080/

Post direct links and make redirect to thank you

---

website/_includes/footer.html
website/css/docs.scss
website/css/landing-page.scss
website/eula/index.md

\cc @kirovboris @Nuarat 
Add an EULA page and a link to this page from the footer.
http://strelyaev-w8:8080/eula/

Add an EULA

---

website/tweets/tweets.json

Twitter changed rendering and one tweet became too high. Replaced it with a different tweet @Nuarat suggested.

Replace a long tweet

---

documentation/getting-started/README.md
documentation/user-interface/record-configuration-dialog.md
documentation/user-interface/run-configurations-dialog.md
documentation/working-with-testcafe-studio/recording-tests/README.md
documentation/working-with-testcafe-studio/recording-tests/test-actions/README.md
documentation/working-with-testcafe-studio/reports.md
documentation/working-with-testcafe-studio/running-tests.md

Add links to new topics

---

website/_includes/footer.html

Change the footer text according to Ray's request

Change the footer text

---

website/_includes/head.html

Load Twitter scripts through HTTPS

---

documentation/user-interface/README.md

Add missing links to the 'UI' root topic

---

documentation/guides/record-tests/README.md
documentation/guides/run-tests.md
documentation/references/README.md
documentation/references/supported-browsers.md
website/nav/nav-menu.yml

Supported browsers

---

documentation/guides/record-tests/test-actions/assertions.md
documentation/user-interface/record-configuration-dialog.md
documentation/user-interface/run-configurations-dialog.md

assertion timeout

---

.gitignore
documentation/guides/organize-tests.md

and update `.gitignore`
\cc @MargaritaLoseva

Fix a broken link

---

website/robots.txt

[docs] Disallow robots to index the survey

---

website/_data/videos.json
website/_includes/youtube-video-init.html

\cc @MargaritaLoseva @helen-dikareva 
Post the new overview video: https://testcafe-studio.devexpress.in/documentation/video-tutorials/

[docs] Update the overview video

---

website/scripts/survey.js

[docs] Add a counter to the complete survey button
